### ISSUE TITLE
Updated version deployed to rubygems?

### ISSUE THREAD

**Issue by sax** [adamhjk/dynect_rest#37]
There are a number of fixes in the source code that are not available in Rubygems. Because they're not actually released, deploying them to our infrastructure would require writing our own chef deployment code, as the chef_gem seems to only work with released gems.

We're currently running into frequent errors when running this gem, errors that appear to be handled in master. Could these updates be released?

**Comment by ranjib** [comment]
@sax @murphy-slaw This gem has not been abandoned. In between, Dynect had informed us about another ruby-sdk, so i was under dilemma. But it looks like theres no progress on that front for quiet some time. So I have updated couple of stuff and released a new version. We extensively use this gem :-), so dont worry.
